require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PaintersController do

  # This should return the minimal set of attributes required to create a valid
  # Painter. As you add validations to Painter, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PaintersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all painters as @painters" do
      painter = Painter.create! valid_attributes
      get :index, {}, valid_session
      assigns(:painters).should eq([painter])
    end
  end

  describe "GET show" do
    it "assigns the requested painter as @painter" do
      painter = Painter.create! valid_attributes
      get :show, {:id => painter.to_param}, valid_session
      assigns(:painter).should eq(painter)
    end
  end

  describe "GET new" do
    it "assigns a new painter as @painter" do
      get :new, {}, valid_session
      assigns(:painter).should be_a_new(Painter)
    end
  end

  describe "GET edit" do
    it "assigns the requested painter as @painter" do
      painter = Painter.create! valid_attributes
      get :edit, {:id => painter.to_param}, valid_session
      assigns(:painter).should eq(painter)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Painter" do
        expect {
          post :create, {:painter => valid_attributes}, valid_session
        }.to change(Painter, :count).by(1)
      end

      it "assigns a newly created painter as @painter" do
        post :create, {:painter => valid_attributes}, valid_session
        assigns(:painter).should be_a(Painter)
        assigns(:painter).should be_persisted
      end

      it "redirects to the created painter" do
        post :create, {:painter => valid_attributes}, valid_session
        response.should redirect_to(Painter.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved painter as @painter" do
        # Trigger the behavior that occurs when invalid params are submitted
        Painter.any_instance.stub(:save).and_return(false)
        post :create, {:painter => { "name" => "invalid value" }}, valid_session
        assigns(:painter).should be_a_new(Painter)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Painter.any_instance.stub(:save).and_return(false)
        post :create, {:painter => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested painter" do
        painter = Painter.create! valid_attributes
        # Assuming there are no other painters in the database, this
        # specifies that the Painter created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Painter.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => painter.to_param, :painter => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested painter as @painter" do
        painter = Painter.create! valid_attributes
        put :update, {:id => painter.to_param, :painter => valid_attributes}, valid_session
        assigns(:painter).should eq(painter)
      end

      it "redirects to the painter" do
        painter = Painter.create! valid_attributes
        put :update, {:id => painter.to_param, :painter => valid_attributes}, valid_session
        response.should redirect_to(painter)
      end
    end

    describe "with invalid params" do
      it "assigns the painter as @painter" do
        painter = Painter.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Painter.any_instance.stub(:save).and_return(false)
        put :update, {:id => painter.to_param, :painter => { "name" => "invalid value" }}, valid_session
        assigns(:painter).should eq(painter)
      end

      it "re-renders the 'edit' template" do
        painter = Painter.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Painter.any_instance.stub(:save).and_return(false)
        put :update, {:id => painter.to_param, :painter => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested painter" do
      painter = Painter.create! valid_attributes
      expect {
        delete :destroy, {:id => painter.to_param}, valid_session
      }.to change(Painter, :count).by(-1)
    end

    it "redirects to the painters list" do
      painter = Painter.create! valid_attributes
      delete :destroy, {:id => painter.to_param}, valid_session
      response.should redirect_to(painters_url)
    end
  end

end
